syntax = "proto3";

package gophkeeper;

option go_package = "github.com/serg2014/go-goph-keeper/cmd/server/proto";

message RegisterUserRequest{
    string login = 1;
    string password = 2;
}
message JWTToken {
    string token = 1;
}
message RegisterUserResponse{
    JWTToken access = 1;
    JWTToken refresh = 2;
}
message AuthUserRequest{
    string login = 1;
    string password = 2;
}
message AuthUserResponse{
    JWTToken access = 1;
    JWTToken refresh = 2;
}

message RenewAuthRequest{}
message RenewAuthResponse {
    JWTToken access = 1;
    JWTToken refresh = 2;
}
service AuthService {
    rpc RegisterUser(RegisterUserRequest) returns (RegisterUserResponse);
    rpc AuthUser(AuthUserRequest) returns (AuthUserResponse);
    rpc RenewAuth(RenewAuthRequest) returns (RenewAuthResponse);
}

message PingRequest {}
message PingResponse {}

message SecretData {
    int64 updated_at = 1;
    bytes data = 2;
}
message Secret {
    string id = 1;
    SecretData meta = 2;
    SecretData data = 3;
}
message CreateSecretRequest{
    Secret secret = 1;
}

message CreateSecretResponse{
    string id = 1;
    bool conflict = 2;
}

message UpdateRequestInfo {
    int64 updated_at = 2;
    int64 version = 3;
    bytes data = 4;  
}
message UpdateSecretRequest {
    string id = 1;
    UpdateRequestInfo meta = 2;
    UpdateRequestInfo data = 3;
}

message UpdateResponseInfo {
    int64 version = 1;
}
message UpdateSecretResponse {
    string id = 1;
    bool conflict = 2;
    UpdateResponseInfo meta = 3;
    UpdateResponseInfo data = 4;
}

service GophKeeperService {
    rpc Ping(PingRequest) returns (PingResponse);
    rpc CreateSecrets(stream CreateSecretRequest) returns (stream CreateSecretResponse);
    rpc UpdateSecrets(stream UpdateSecretRequest) returns (stream UpdateSecretResponse);
}
